### ISSUE TITLE
Dockerize

### ISSUE THREAD

**Issue by Astro-ton618** [Astro-ton618/repograph#4]
Insert the project inside a docker container

**Comment by DipayanP007** [comment]
I would like to work on this. I think I can do it.

**Comment by Astro-ton618** [comment]
Thank you, I know you can do it👍, love to have you on board

**Comment by DipayanP007** [comment]
I have created the pull request with the Dockerfile. Thank you :smile:

**Comment by DipayanP007** [comment]
#6
